#!/usr/bin/env bash
# =============================================================================
# log-trace.sh — PostToolUse work-trace logger
# -----------------------------------------------------------------------------
# Fires after every Write / Edit / MultiEdit / NotebookEdit tool call.
# Reads the hook payload (JSON) from stdin, figures out which file was touched,
# summarises the change (what changed, how big, key diff lines) and appends a
# dated entry to docs/work-trace/trace-log.md.
#
# Design goals:
#   * Never block the agent — always exit 0, even on partial failure.
#   * Zero hard dependencies: uses `jq` if available, else a grep/sed fallback.
#   * Deterministic, append-only, grouped by UTC date.
#
# Hook stdin payload (Claude Code PostToolUse) looks roughly like:
#   { "tool_name": "Edit",
#     "tool_input": { "file_path": "src/x.astro", ... },
#     "cwd": "/repo", ... }
# =============================================================================
set -uo pipefail

# --- resolve repo root (fall back to cwd) -----------------------------------
REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$REPO_ROOT" 2>/dev/null || exit 0

TRACE_DIR="docs/work-trace"
TRACE_LOG="$TRACE_DIR/trace-log.md"
mkdir -p "$TRACE_DIR"

# --- read hook payload from stdin -------------------------------------------
PAYLOAD="$(cat 2>/dev/null || true)"

# --- tiny JSON extractor: prefers jq, degrades to grep/sed ------------------
json_get() {
  # $1 = dotted path like .tool_input.file_path
  local path="$1"
  if command -v jq >/dev/null 2>&1; then
    printf '%s' "$PAYLOAD" | jq -r "$path // empty" 2>/dev/null
  else
    # naive fallback: grab the last key segment as a flat "key": "value"
    local key="${path##*.}"
    printf '%s' "$PAYLOAD" \
      | grep -o "\"$key\"[[:space:]]*:[[:space:]]*\"[^\"]*\"" \
      | head -n1 \
      | sed -E "s/.*:[[:space:]]*\"([^\"]*)\"/\1/"
  fi
}

TOOL="$(json_get '.tool_name')";        TOOL="${TOOL:-unknown-tool}"
FILE="$(json_get '.tool_input.file_path')"
[ -z "$FILE" ] && FILE="$(json_get '.tool_input.notebook_path')"
[ -z "$FILE" ] && FILE="$(json_get '.tool_input.path')"

# If we could not determine a file, there is nothing useful to trace.
[ -z "$FILE" ] && exit 0

# Relative path for readability
REL="${FILE#$REPO_ROOT/}"

NOW_UTC="$(date -u +'%Y-%m-%d %H:%M:%S UTC')"
DAY_UTC="$(date -u +'%Y-%m-%d')"

# --- compute a diff summary against git working tree ------------------------
# Use `git diff` (unstaged) so we capture what the agent just wrote.
ADDED=0; REMOVED=0; STATUS="modified"; DIFF_BODY=""
if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  if ! git ls-files --error-unmatch -- "$REL" >/dev/null 2>&1; then
    STATUS="created (untracked)"
  fi
  # numstat gives "added<TAB>removed<TAB>file" (against HEAD for full picture)
  NUMSTAT="$(git diff --numstat HEAD -- "$REL" 2>/dev/null | head -n1)"
  if [ -n "$NUMSTAT" ]; then
    ADDED="$(printf '%s' "$NUMSTAT"  | cut -f1)"
    REMOVED="$(printf '%s' "$NUMSTAT" | cut -f2)"
  fi
  # Capture up to 12 meaningful changed lines (skip hunk noise) for context.
  DIFF_BODY="$(git diff HEAD -- "$REL" 2>/dev/null \
    | grep -E '^[+-]' \
    | grep -vE '^(\+\+\+|---)' \
    | head -n 12)"
fi
[ "$ADDED"   = "-" ] && ADDED="(binary)"
[ "$REMOVED" = "-" ] && REMOVED="(binary)"

# --- write the entry --------------------------------------------------------
# Ensure the file + today's date section header exist.
if [ ! -f "$TRACE_LOG" ]; then
  {
    echo "# Work Trace Log"
    echo
    echo "> Auto-generated by \`.claude/hooks/log-trace.sh\` (PostToolUse hook)."
    echo "> Every AI file modification is recorded below, grouped by UTC date."
    echo "> **Do not edit by hand** — entries are append-only."
    echo
  } >> "$TRACE_LOG"
fi

if ! grep -qxF "## $DAY_UTC" "$TRACE_LOG" 2>/dev/null; then
  {
    echo "## $DAY_UTC"
    echo
  } >> "$TRACE_LOG"
fi

{
  echo "### \`$REL\` — $STATUS"
  echo
  echo "- **When:** $NOW_UTC"
  echo "- **Tool:** $TOOL"
  echo "- **Change size:** +$ADDED / -$REMOVED lines"
  echo "- **What:** AI ${STATUS%% *} \`$REL\` via $TOOL."
  echo "- **How:** direct file write by the coding agent (no manual editing)."
  echo "- **Note:** review the diff before committing; treated as 0% hand-written code."
  if [ -n "$DIFF_BODY" ]; then
    echo
    echo "<details><summary>Key diff (truncated)</summary>"
    echo
    echo '```diff'
    printf '%s\n' "$DIFF_BODY"
    echo '```'
    echo
    echo "</details>"
  fi
  echo
} >> "$TRACE_LOG"

exit 0
